# Generated by Django 5.0.1 on 2024-01-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('T', 'Tişört'), ('P', 'Pantolon'), ('A', 'Ayakkabı'), ('C', 'Ceket'), ('E', 'Elbise')], max_length=2),
        ),
    ]
