# Generated by Django 5.0.1 on 2024-01-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('K', 'Kadın'), ('E', 'Erkek'), ('A', 'Ayakkabı'), ('C', 'Çanta'), ('SG', 'Spor Giyim')], max_length=2),
        ),
    ]
