# Generated by Django 5.0.1 on 2024-01-08 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_remove_address_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='country',
        ),
    ]
